{
 "title": "Github events emailer",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"spring_micrometer\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Processing time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "CamelMessageHistory_seconds_max{nodeId=\"send-email\"}",
     "legendFormat": "Sending out emails"
    },
    {
     "expr": "CamelMessageHistory_seconds_max{nodeId=\"translate-github-events\"}",
     "legendFormat": "Translating events"
    }
   ]
  },
  {
   "title": "Github events",
   "type": "stat",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "CamelMessageHistory_seconds_count{nodeId=\"to-github-events\"}",
     "legendFormat": "Github events accepted"
    },
    {
     "expr": "CamelMessageHistory_seconds_count{nodeId=\"log-ignored-event\"}",
     "legendFormat": "Github events dropped"
    },
    {
     "expr": "CamelMessageHistory_seconds_count{nodeId=\"send-email\"}",
     "legendFormat": "Emails sent"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "CamelExchangesFailed_total{routeId=\"github-webhook\"}",
     "legendFormat": "When accepting events"
    },
    {
     "expr": "CamelExchangesFailed_total{routeId=\"translator\"}",
     "legendFormat": "When converting events into emails"
    },
    {
     "expr": "CamelExchangesFailed_total{routeId=\"email-sender\"}",
     "legendFormat": "When sending out emails"
    }
   ]
  }
 ]
}