= GitHub events emailer

image:https://travis-ci.com/AlexanderZobkov/github-events-emailer.svg?branch=master["Build Status", link="https://travis-ci.com/AlexanderZobkov/github-events-emailer"]
image:https://api.bintray.com/packages/alexander-zobkov/maven/github-events-emailer/images/download.svg[link="https://bintray.com/alexander-zobkov/maven/github-events-emailer/_latestVersion"]
image:https://img.shields.io/docker/v/zobkov/github-events-emailer?label=docker%20hub["Docker Image Version (latest by date)", link="https://hub.docker.com/repository/docker/zobkov/github-events-emailer"]
image:https://img.shields.io/maven-metadata/v?color=informational&label=Latest%20snapshot&metadataUrl=https%3A%2F%2Foss.jfrog.org%2Fartifactory%2Foss-snapshot-local%2Fcom%2Fgithub%2Falexander-zobkov%2Fgithub-events-emailer%2Fmaven-metadata.xml["Latest SNAPSHOT", link="https://oss.jfrog.org/artifactory/oss-snapshot-local/com/github/alexander-zobkov/github-events-emailer/"]

image:https://img.shields.io/github/license/AlexanderZobkov/github-events-emailer[GitHub]


== Build

```shell
./gradlew clean build
```

== Usage

=== Setting up a Webhook

https://developer.github.com/webhooks/creating/

The application supports webhooks that are setup in the following way:

* Payload URL
** It is set with plain HTTP with any path. Secured connection with SSL is not supported yet.
* Content type
** It is set to `application/json`. The `application/x-www-form-urlencoded` content type is not supported yet.
* Secret
** Could be leaved empty or set with any value. Payloads from github are not validated yet.
* Events
** The application will not crash if receive unexpected events
however only the following events will result in an email:
- https://developer.github.com/webhooks/event-payloads/#push[Pushes]
- https://developer.github.com/webhooks/event-payloads/#create[Branch or tag creation]

=== Settings

link:src/main/resources/application.properties[See the configuration file for details].
