name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.adoc'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.adoc'

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 17 ]

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - name: Build artifacts
        run: ./gradlew clean build

      - name: Publish artifacts
        if: matrix.java == '8' && github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: ./gradlew bootBuildImage --publishImage
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
