name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.adoc'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.adoc'

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build artifacts
        run: ./gradlew clean build

      - name: Publish artifacts
        run: ./gradlew bootBuildImage --publishImage
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}

      - name: Run integration tests
        run: ./gradlew integrationTest
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_REPO: ${{ secrets.GH_REPO }}

